### PR TITLE
added google cloud storage driver

### PR DESCRIPTION
**Pull request by stern0**
Implemented google cloud storage driver and tests.
[regards issue](https://github.com/blockstack/gaia/issues/103)

### CODE REVIEW

**Comment by kantai** [comment]
Thanks for this @stern0! We'll get this reviewed and tested soon.

**Comment by kantai** [comment]
Awesome, thanks @stern0 -- I needed to change the upload call a little bit to support using the input streams. Merged into `develop` now.

**Comment by siliconswampio** [comment]
Any help on implementing this? @kantai 

What are the necessary steps to setup the google cloud and information and the details necessary for connecting to the google cloud api? the documentation for this isn't very clear. I have made a config.json but not sure if it correct format and what values are for each key.


    {
      "port": 3000,
      "driver": "google-cloud",
      "readURL": "url.com",
      "bucket": "",
      "pageSize": 20,
      "gcCredentials": {
        "credentials": {
          "client_email": "",
          "private_key": ""
        },
        "email": "",
        "keyFilename": "",
        "projectId": ""
      },
      "argsTransport": {
        "level": "debug",
        "handleExceptions": true,
        "timestamp": true,
        "colorize": false,
        "json": true
      }
    }

**Comment by zone117x** [comment]
@siliconswampio can you post this in a new issue? You're posting in an old PR which won't receive much attention.

**Pull request merged**
