### PR TITLE
updating build versions to tag 2.5.2, shredding some data

### PR DESCRIPTION
**Pull request by wileyj**
## Goal of PR

Update the AWS build image to use tag 2.5.2

## Implementation

N/A
## Manual Testing

N/A

## Automated Testing

N/A

## Submission Checklist

- [x] Based on correct branch: feature submissions should be on `develop`, hotfixes should be on `master`

- [ ] The code passes our eslint definitions, unit tests, and
      contains correct TypeFlow annotations.

- [ ] Submission contains tests that cover any and all new functionality or code changes.

- [ ] Submission documents any new features or endpoints, and describes how developers
      would be expected to interact with them.

- [x] Author has agreed to our contributor's agreement.

### CODE REVIEW

**Comment by zone117x** [comment]
Do want to pull in the 2.5.3 hotfix for this?
https://github.com/blockstack/gaia/pull/233

**Comment by wileyj** [comment]
@zone117x that's fine. 
These changes don't affect the service whatsoever so they can be added to any other PR or combined with another PR.

**Comment by wileyj** [comment]
Of note though: until these changes are in master, I'm blocked from building the image for AWS marketplace (there may be more changes required after their review, but this should address most of them)

**Comment by zone117x** [comment]
@wileyj 2.5.3 merged to master

**Pull request merged**
