### PR TITLE
Deprecate timestamps

### PR DESCRIPTION
**Pull request by kantai**
This deprecates the annual timestamp in the challenge text -- it just replaces it with '0'.

This incorporates legacy years (2018, 2019) in challenge text checks as well.

### CODE REVIEW

**Comment by jcnelson** [comment]
Is my understanding correct in that a Gaia auth token is basically valid forever if it sets its span to `0`?  Or do Gaia auth tokens still expire (or have a revocation option)?

**Comment by kantai** [comment]
There's an `exp` field in the JWT for setting an expiration time which Gaia auth respects. Legacy tokens _don't_ have such a field, however, legacy tokens are problematic in other ways, and haven't been generated in any libraries for at least 6 months.

**Comment by jcnelson** [comment]
Okay, sounds good.  As long as tokens expire per the `exp` field, this PR looks good to me :+1:

**Comment by kantai** [comment]
Thanks for the review @jcnelson -- tagging @zone117x for a review as well before merging.

**Comment by kantai** [comment]
Great, thanks for the reviews! Merging.

**Pull request merged**
